;
; routine.inc -- Header file related to generic routines
;
; Copyright (C) 2007 - 2009, Merck Hung
; Author : Merck Hung <merckhung@gmail.com>
;


;
; Number of bits per ASCII byte
;
NBPAB       EQU     4


; Key code define
UP          EQU     4800h
LEFT        EQU     4b00h
RIGHT       EQU     4d00h
DOWN        EQU     5000h
PGUP        EQU     4900h
PGDN        EQU     5100h

KENTER      EQU     1c0dh


COLUMN      EQU     80
LINE        EQU     25

BCOLUMN     EQU     COLUMN * 2


